### ISSUE TITLE
ライセンス表記について

### ISSUE THREAD

**Issue by tak0kada** [YutaroOgawa/Deep-Reinforcement-Learning-Book#12]
今この教科書を読んでいるのですが、勉強過程で自分用に整理した参考実装を公開したいと思っております。何らかのOSSライセンスを明示して頂けると幸いです。

**Comment by YutaroOgawa** [comment]
@tak0kada さま

本件、誠にありがとうございます。

LICENSEファイルを用意しました（MITライセンスです、ただし引用部分は引用先に従ってください）
https://github.com/YutaroOgawa/Deep-Reinforcement-Learning-Book/blob/master/LICENSE

どうぞよろしくお願い致します。

**Comment by tak0kada** [comment]
素早い対応ありがとうございます！

**Comment by YutaroOgawa** [comment]
@tak0kada さま

こちらこそ、誠にありがとうございます。
今後ともどうぞよろしくお願いします！
